# SPDX-License-Identifier: Apache-2.0
# Copyright 2020-present Intel Corporation
# Copyright 2025 Canonical Ltd.

# Timeline for each ecosystem is intentionally staggered to spread
# Dependabot PRs over the week.
version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "docker"
    directory: "/ptf"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "21:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "21:00"
      timezone: "America/Los_Angeles"
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "21:00"
      timezone: "America/Los_Angeles"
    groups:
      actions-deps:
        patterns:
          - "*"
