name: Docker image

on:
  push:
    branches:
      - master
      - test-docker-ci

jobs:
  build:
    env:
      DOCKER_REGISTRY: "docker.pkg.github.com/omec-project/"
      DOCKER_REPOSITORY: "upf-epc/"
    runs-on: ubuntu-latest
    steps:
    # Checkout and build
    - uses: actions/checkout@v1
    - name: Docker login GH packages
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login https://docker.pkg.github.com -u $USERNAME -p $PASSWORD
    - name: Build and push Docker image
      run: |
        make docker-build
        make docker-push
