# SPDX-License-Identifier: Apache-2.0
# Copyright 2020 Intel Corporation
name: Docker image

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    env:
      DOCKER_REGISTRY: "ghcr.io/omec-project/"
      DOCKER_REPOSITORY: "upf-epc/"
    runs-on: ubuntu-latest
    steps:
    # Checkout and build
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1.14.1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
    - name: Build and push Docker image
      run: |
        make docker-build
        make docker-push

  push-dockerhub:
    env:
      DOCKER_REGISTRY: "docker.io/"
      DOCKER_REPOSITORY: "omecproject/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo GIT_SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - id: docker-login
        uses: docker/login-action@v1.14.1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push "master-latest" Docker images for Haswell CPU
        env:
          DOCKER_TAG: master-latest
          CPU: haswell
        run: |
          docker pull ${DOCKER_REPOSITORY}upf-epc-bess:$DOCKER_TAG
          docker pull ${DOCKER_REPOSITORY}upf-epc-pfcpiface:$DOCKER_TAG
          CPU=$CPU make docker-build
          make docker-push

      - name: Build and push "master-GIT_SHA" Docker images for Haswell CPU
        env:
          DOCKER_TAG: master-latest-${{ env.GIT_SHA_SHORT }}
          CPU: haswell
        run: |
          CPU=$CPU make docker-build
          make docker-push

      - name: Build and push "master-latest-ivybridge" Docker images for Ivybridge CPU
        env:
          DOCKER_TAG: master-latest-ivybridge
          CPU: ivybridge
        run: |
          docker pull ${DOCKER_REPOSITORY}upf-epc-bess:$DOCKER_TAG
          docker pull ${DOCKER_REPOSITORY}upf-epc-pfcpiface:$DOCKER_TAG
          CPU=$CPU make docker-build
          make docker-push

      - name: Build and push "master-GIT_SHA-ivybridge" Docker images for Ivybridge CPU
        env:
          DOCKER_TAG: master-latest-ivybridge-${{ env.GIT_SHA_SHORT }}
          CPU: ivybridge
        run: |
          CPU=$CPU make docker-build
          make docker-push
