# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Intel Corporation

# This is a basic workflow that is manually triggered

name: BESS Build Base Image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
jobs:
  build:
    env:
      REPO: "ghcr.io/omec-project/upf-epc/bess_build"
      TAG: "latest"
      BESS_DPDK_BRANCH: "dpdk-2011-focal"
      DOCKER_PULL: ""
    runs-on: ubuntu-20.04
    steps:
    - name: docker build
      run: |
        git clone -b ${{ env.BESS_DPDK_BRANCH }} https://github.com/NetSys/bess.git
        cd bess/env
        yes n | ./rebuild_images.py focal64
        docker tag nefelinetworks/bess_build:latest ${{ env.REPO }}:${{ env.TAG }}
    - uses: actions/checkout@v3
    - name: Build UPF with new base
      run: |
        make docker-build
    - uses: docker/login-action@v1.14.1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
    - name: docker push
      run: |
        docker push ${{ env.REPO }}:${{ env.TAG }}
