# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-present Open Networking Foundation
name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test-pfcpiface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2

      - name: Run unit tests for PFCP Agent
        run: |
          make test
